### ISSUE TITLE
Ignores the 'columns' definition

### ISSUE THREAD

**Issue by 29er** [agracio/ts-react-json-table#1]
Hey, I was excited to see this lib, but upon first attempt at getting it to work, it completely ignores the columns definition.
simple example will not work.
```
var items = [
  { name: 'Louise', age: 27, color: 'red' },
  { name: 'Margaret', age: 15, color: 'blue'},
  { name: 'Lisa', age:34, color: 'yellow'}
];

var columns = [
    'name',
    {key: 'age', label: 'Age'},
    {key: 'color', label: 'Colourful', cell: function( item, columnKey ){
        return <span style={{color: item.color}}>{item.color} testing</span>;
    }}
];

...

render() {

    //const { rows } = this.state;
    return  (
      <JsonTable rows={items} colums={columns} />
    );
  }
```

are you not supporting this like the 'react-json-table' ? working codepen here:
https://codepen.io/arqex/pen/waJREq?editors=0110

thanks

**Comment by agracio** [comment]
Not really sure why you would have this issue **_columns_** prop is fully supported, here is JsFiddle using the code in your example https://jsfiddle.net/agracio/2dd7sxxs/

**Comment by 29er** [comment]
your example worked ... ok sorry for the false alarm. must have been a typo. thanks!
