### ISSUE TITLE
cellClass function - rowData parameter not full row

### ISSUE THREAD

**Issue by bradtwurst** [agracio/ts-react-json-table#2]
In react json table, the cellClass function returns the full rowData item.

In ts-react-json-table, the cellClass function appears to be returning only the current cell value, not the entire row.

Am I missing something?

Thanks,
James

**Comment by agracio** [comment]
Looks like you right, I will fix it withing the next couple of days.

**Comment by agracio** [comment]
PR merged and new packaged is now on NPM, thanks for your help.
