### ISSUE TITLE
Possibility of editing a column field but still retaining all the columns

### ISSUE THREAD

**Issue by jasdeep06** [agracio/ts-react-json-table#5]
Hi!
Thanks for this great component!
I'm using this library to render my JSON in form of tables.A fairly common operation from me is to add links to particular columns.I can use `columns` for that,which I am.
The problem is I want to render every other field too.This,I think is only possible if I mention all the column names in column prop along with edited fields.Is there a better way?
Following code explains better-

```
var items = [
  {"id": 75950,"name": "Louella Wallace","age": 24,"phone": "+44 (0)203 437 7302","color": "green"},
  {"id": 80616,"name": "Hanson Perry","age": 36,"phone": "+44 (0)203 279 3708","color": "brown"},
  {"id": 77621,"name": "Brandi Long","age": 20,"phone": "+44 (0)203 319 4880","color": "gray"},
  {"id": 81299,"name": "Tonia Sykes","age": 38,"phone": "+44 (0)208 328 3671","color": "blue"},
  {"id": 14225,"name": "Leach Durham","age": 23,"phone": "+44 (0)208 280 9572","color": "green"}
];

var columns = [
    {key: 'color', label: 'Colourful', cell: function( row, columnKey ){
        return <span style={{color: row.color}}>{row.color}</span>;
    }}
];


ReactDOM.render( <JsonTable className="table table-striped" rows = {items} columns={columns} / > ,
  document.getElementById('container')
);
```

In above code,I want to list all the columns without listing their names(Since there are host of them in my usecase).

**Comment by agracio** [comment]
This is not supported. If you specify `columns` you need to include all items that you want to render.

**Comment by jasdeep06** [comment]
Thanks for the response @agracio .
I've used onClickCell function which does this!

**Comment by agracio** [comment]
Of course, I forgot about this one.
