### ISSUE TITLE
Feature request: Sticky header

### ISSUE THREAD

**Issue by David-dp-** [agracio/ts-react-json-table#7]
Do you already support a way of keeping the header visible while body cells may be scrolled vertically? If not, would you please add this?

**Comment by agracio** [comment]
It is not supported and would be very hard to implement using the current structure requiring complete refactoring of the table rendering code.

**Comment by David-dp-** [comment]
Thank you for the explanation. I'll weigh whether we need this feature enough to switch to a different table library.
